export const biomarkers = {
  cholesterol: {
    title: 'Cholesterol total',
    normal_range: [[0.0, 5.2]],
    abnormal_range: [[5.2, 99]],
    optimal_range: [[0.0, 5.2]],
    unit: 'mmol/L',
    desc: 'Cholesterol is a steroid lipid present in the bloodstream and cell membranes, essential for synthesising hormones, vitamin D, and bile acids necessary for fat digestion. It plays a critical role in maintaining cell membrane structure and fluidity and is fundamental for the formation of myelin sheaths around nerve fibres.',
  },
  ldlCholesterol: {
    title: 'LDL Cholesterol',
    normal_range: [[0.0, 3.5]],
    abnormal_range: [[3.5, 99]],
    optimal_range: [[0.0, 3.5]],
    unit: 'mmol/L',
    desc: 'Commonly referred to as "bad" cholesterol, elevated LDL levels can contribute to atherosclerosis by promoting arterial plaque formation, thereby increasing the risk of cardiovascular diseases.',
  },
  hdlCholesterol: {
    title: 'HDL Cholesterol',
    normal_range: [[1.0, 2.0]],
    abnormal_range: [[0.0, 1.0]],
    optimal_range: [[2.0, 99]],
    unit: 'mmol/L',
    desc: 'Known as "good" cholesterol, HDL aids in removing excess cholesterol from the bloodstream and provides protection against cardiovascular disease.',
  },
  nonHdlCholesterol: {
    title: 'Non HDL Cholesterol',
    normal_range: [[3.5, 4.2]],
    abnormal_range: [[4.2, 99]],
    optimal_range: [[0.0, 3.5]],
    unit: 'mmol/L',
    desc: 'NON HDL cholesterol represents the total circulating cholesterol not carried by HDL (high-density lipoprotein). It includes all potentially harmful cholesterol types, such as LDL (low-density lipoprotein) and VLDL (very low-density lipoprotein). Elevated levels of non-HDL cholesterol are associated with an increased risk of cardiovascular disease and related events, as they contribute to the buildup of cholesterol in arterial walls, leading to atherosclerosis and other heart-related conditions.',
  },
  triglyceride: {
    title: 'Triglycerides',
    normal_range: [[0.0, 1.7]],
    abnormal_range: [[1.7, 99]],
    optimal_range: [[0.0, 1.0]],
    unit: 'mmol/L',
    desc: 'Triglycerides consist of fatty acid molecules that enter the bloodstream either through the liver or from dietary intake. Elevated triglyceride levels can be seen in conditions such as fatty liver disease, increased risk of cardiovascular disease, metabolic syndrome, adrenal dysfunction and hypothyroidism. Consistently consuming more calories than you expend, especially from high-carbohydrate foods, lead to elevated triglyceride levels.',
  },
  cholesterolToHdlRatio: {
    title: 'Cholesterol / HDL Ratio',
    normal_range: [[3.0, 6.0]],
    abnormal_range: [[6.0, 99]],
    optimal_range: [[0.0, 3.0]],
    unit: 'ratio',
    desc: 'The Cholesterol/HDL ratio is a measure used to assess cardiovascular risk by comparing the total cholesterol level in the blood to the level of HDL (high-density lipoprotein) cholesterol. This ratio provides insight into the balance between "bad" cholesterol (which contributes to plaque formation in arteries) and "good" cholesterol (which helps remove cholesterol from the bloodstream). A higher Cholesterol/HDL ratio indicates a greater risk of developing cardiovascular disease, while a lower ratio suggests a more favourable lipid profile and a lower risk of heart-related issues.',
  },
  glucose: {
    title: 'Glucose',
    normal_range: [[5.0, 6.0]],
    abnormal_range: [[6.0, 99]],
    optimal_range: [[0.0, 5.0]],
    unit: 'mmol/L',
    desc: 'Fasting glucose is a critical indicator of metabolic health, reflecting the delicate balance of glucose regulation in the body. This balance is primarily maintained by the hormones insulin and glucagon. Fasting glucose levels provide important insights into how effectively the body manages blood sugar, with abnormal levels potentially indicating conditions such as diabetes or insulin resistance.',
  },
  hbA1c: {
    title: 'HbA1C',
    normal_range: [
      [0.0, 4.6],
      [5.3, 6.0],
    ],
    abnormal_range: [[6.0, 99]],
    optimal_range: [[4.6, 5.3]],
    unit: '%',
    desc: 'The HbA1C test measures the average blood glucose levels over the past 2 to 3 months by assessing the percentage of hemoglobin glycated by glucose. As red blood cells have a lifespan of approximately 120 days, higher blood glucose levels result in increased glycation of hemoglobin. A higher HbA1C percentage indicates elevated average blood glucose. Optimal levels are below 4.6 - 5.3%, prediabetes ranges from 6% to 6.9%, and diabetes is indicated by 7% or higher. This test is essential for monitoring long-term glucose control and diagnosing diabetes.',
  },
  insulin: {
    title: 'Insulin',
    normal_range: [[60.0, 180.0]],
    abnormal_range: [
      [0.0, 15.0],
      [180.0, 999],
    ],
    optimal_range: [[15.0, 60.0]],
    unit: 'pmol/L',
    desc: "Insulin fasting measures insulin levels in the blood after a 12-hour fast. Insulin, released by the pancreas, regulates glucose uptake and storage. Insulin resistance, where cells can't effectively use insulin, leads to high insulin levels, increasing the risk of stroke, diabetes, metabolic syndrome, and heart attack.",
  },
  creatinine: {
    title: 'Creatinine',
    normal_range: [[50.0, 117.0]],
    abnormal_range: [
      [0.0, 50.0],
      [117.0, 999],
    ],
    optimal_range: [[50.0, 117.0]],
    unit: 'umol/L',
    desc: 'Creatinine is a chemical waste product that is produced continuously during normal muscle breakdown and is normally excreted by the kidneys. Creatine phosphate serves as a reservoir for muscle energy. Any disorder affecting the kidneys or urinary tract can impair creatinine excretion, leading to elevated serum levels. Additionally, elevated creatinine levels may also suggest prostate dysfunction. Overall, creatinine levels provide a more specific and sensitive indicator of renal disease compared to Blood Urea Nitrogen (BUN). If serum creatinine levels decrease, it may be due to muscle atrophy or nerve-muscle degeneration. If serum creatinine levels are high, consider impaired renal function due to a potential renal disease.',
  },
  eGFR: {
    title: 'eGFR',
    normal_range: [[60.0, 99.0]],
    abnormal_range: [[0.0, 60.0]],
    optimal_range: [[99.0, 999]],
    unit: 'mL/min/1.73 m²',
    desc: 'eGFR, or estimated Glomerular Filtration Rate, is a measure used to assess how well the kidneys are filtering blood. It estimates the rate at which the kidneys are clearing creatinine from the bloodstream, providing an indication of overall kidney function. The eGFR is calculated using a formula that incorporates factors such as serum creatinine levels, age, sex, and race. It helps in diagnosing and monitoring kidney diseases and is a key parameter in evaluating kidney health. Levels below 60 mL/min/1.73 m² indicate a reduction in kidney function and may require a consultation with a nephrologist for further evaluation.',
  },
  calcium: {
    title: 'Calcium',
    normal_range: [
      [2.15, 2.22],
      [2.45, 2.6],
    ],
    abnormal_range: [
      [0.0, 2.15],
      [2.6, 99],
    ],
    optimal_range: [[2.22, 2.45]],
    unit: 'mmol/L',
    desc: "Serum calcium levels are carefully maintained within a narrow range (2.22–2.60 mmol/L) and are primarily regulated by parathyroid hormone (PTH) and vitamin D. Low calcium levels suggest an imbalance in calcium regulation rather than a direct deficiency. It's important to assess vitamin D levels, rule out hypochlorhydria, and evaluate the need for magnesium, phosphorus, vitamins A, B, and C, unsaturated fatty acids, and iodine before considering calcium supplementation. Elevated calcium levels are often linked to parathyroid hyperfunction. If significantly high (>2.65 mmol/L), PTH levels should be checked, and referral to an endocrinologist may be necessary. PTH increases serum calcium by stimulating bone resorption, increasing renal calcium reabsorption, promoting vitamin D activation, and enhancing intestinal calcium absorption. Many calcium issues stem from impaired absorption or utilization rather than actual deficiency. As part of calcium is bound to albumin, serum albumin levels should be evaluated to avoid misinterpreting total serum calcium levels.",
  },
  magnesium: {
    title: 'Magnesium',
    normal_range: [[0.65, 0.9]],
    abnormal_range: [
      [0.0, 0.65],
      [1.1, 99],
    ],
    optimal_range: [[0.9, 1.1]],
    unit: 'mmol/L',
    desc: "Magnesium is vital for various enzymatic processes including carbohydrate metabolism, protein and nucleic acid synthesis, muscle contraction, energy production, and blood clotting. It supports bone health, blood pressure regulation, and blood sugar control. Magnesium is found in leafy greens, nuts, seeds, and whole grains. Elevated levels can be due to kidney dysfunction or hypothyroidism, while deficiency can lead to cramps, fatigue, and arrhythmias. About half of the body's magnesium is in soft tissue and muscle, the rest in bones. Only ~30% of dietary magnesium is absorbed, mostly in the small intestine. Since most magnesium is intracellular, serum magnesium is not the most reliable indicator—RBC magnesium testing is preferred. Magnesium and serum albumin are closely linked; albumin fluctuations can affect serum magnesium levels.",
  },
  magnesiumRbc: {
    title: 'Magnesium RBC',
    normal_range: [[4.0, 5.5]],
    abnormal_range: [
      [0.0, 4.0],
      [6.4, 99],
    ],
    optimal_range: [[5.5, 6.4]],
    unit: 'mg/dL',
    desc: 'RBC magnesium provides a more accurate assessment of magnesium status than serum levels, as red blood cells contain 2–3 times the magnesium concentration found in serum. Magnesium is essential for over 300 enzymatic reactions, energy production, protein and DNA synthesis, and muscle and nerve function. Deficiency is linked to fatigue, cramps, and cardiac arrhythmias. Sources include leafy greens, nuts, seeds, and whole grains. Only about a third of dietary magnesium is absorbed. Since magnesium is mostly intracellular, RBC testing is more reflective of magnesium stores. Magnesium status also depends on albumin levels, and hypoalbuminemia can skew magnesium readings. Magnesium metabolism is closely tied to serum levels, and dysfunction in one can affect the other.',
  },
  zinc: {
    title: 'Zinc',
    normal_range: [[7.8, 12.0]],
    abnormal_range: [
      [0.0, 7.8],
      [16.8, 99],
    ],
    optimal_range: [[12.0, 16.8]],
    unit: 'umol/L',
    desc: 'Zinc is a critical trace mineral involved in immune function, protein and DNA synthesis, antioxidant defense, hormone regulation, and neurological health. Found in meat, seafood, and nuts, zinc supports metabolic functions including immune response and tissue repair. Deficiency may impair immunity, wound healing, and growth, while excess zinc can lead to toxicity—causing nausea, gastrointestinal discomfort, and interference with copper absorption. Zinc plays a central role in enzyme function, hormone activity (e.g., testosterone), and antioxidant pathways such as superoxide dismutase (SOD).',
  },
  ferritin: {
    title: 'Ferritin',
    normal_range: [
      [12.0, 90.0],
      [200.0, 543.0],
    ],
    abnormal_range: [
      [0.0, 12.0],
      [543.0, 999],
    ],
    optimal_range: [[90.0, 200.0]],
    unit: 'ug/L',
    desc: "Ferritin is the primary intracellular protein for storing and releasing iron, found in the liver, spleen, bone marrow, and blood. Serum ferritin is a key marker for assessing iron stores. Low ferritin indicates iron deficiency, potentially leading to anemia, fatigue, and pallor. Elevated levels may suggest inflammation, liver dysfunction, oxidative stress, or iron overload conditions like hemochromatosis. Managing high ferritin involves lifestyle and dietary changes to prevent organ damage. It's crucial to evaluate ferritin in context with CRP, liver enzymes, and transferrin saturation to distinguish between inflammation and true iron overload.",
  },
  seleniumPlasma: {
    title: 'Selenium Plasma',
    normal_range: [[105.3, 120.0]],
    abnormal_range: [
      [0.0, 105.3],
      [160.4, 999],
    ],
    optimal_range: [[120.0, 160.4]],
    unit: 'ug/L',
    desc: 'Selenium is an essential trace element involved in the function of antioxidant enzymes (like glutathione peroxidase), thyroid hormone metabolism, immune defense, and DNA synthesis. Rich dietary sources include Brazil nuts, seafood, and whole grains. Selenium has a narrow therapeutic window—deficiency can impair immune and cognitive function, cause muscle pain, pigmentation loss, or macrocytosis, while toxicity may result in brittle hair, garlic breath, skin swelling, and joint pain. Plasma selenium helps assess long-term status and potential imbalances affecting thyroid function or oxidative stress regulation.',
  },
  sedimentationRate: {
    title: 'ESR',
    normal_range: [[5.0, 30.0]],
    abnormal_range: [
      [0.0, 2.0],
      [30.0, 99],
    ],
    optimal_range: [[2.0, 10.0]],
    unit: 'mm/hr',
    desc: 'The Erythrocyte Sedimentation Rate (ESR) test works by measuring how certain blood proteins change in response to inflammation, leading to the clumping of red blood cells. This test is a non-specific marker of inflammation in the body. It is commonly used to assess the extent of tissue damage, gauge inflammation levels, and indicate if an underlying disease process may be present and requires further investigation. An ESR above 10mm/hr often indicates tissue inflammation, which can be associated with conditions such as rheumatoid arthritis (RA), gout, arthritis, endocarditis, systemic lupus erythematosus (SLE), and nephrosis. It can also be seen in cases of carcinoma, neoplasms, lymphoma, and various autoimmune processes. Additionally, elevated ESR levels may be observed in acute uncomplicated viral diseases, active allergies, peptic ulcers, infectious mononucleosis, and in cases of active renal failure combined with heart failure.',
  },
  cReactiveProtein: {
    title: 'hs CRP',
    normal_range: [[1.0, 4.0]],
    abnormal_range: [[4.0, 99]],
    optimal_range: [[0.0, 1.0]],
    unit: 'mg/L',
    desc: 'The high-sensitivity C-Reactive Protein (hs-CRP) test is to measure low levels of CRP protein produced by the liver in response to inflammation. The "high-sensitivity" version of the test is designed to detect even small increases in CRP, making it a useful tool for assessing the risk of cardiovascular diseases, such as heart attacks and strokes. Elevated hs-CRP levels can indicate low-grade inflammation in the arteries, which may be associated with an increased risk of cardiovascular events and diabetes. High-sensitivity-CRP levels above >1 mg/L may indicate the presence of low-grade inflammation in the body, which is often associated with an increased risk of cardiovascular diseases such as heart attacks, strokes, and atherosclerosis. High hs-CRP levels can also suggest the presence of other inflammatory conditions, including acute viral infections, chronic inflammatory diseases like rheumatoid arthritis, abdominal obesity, high blood pressure, periodontal disease, diabetes, Alzheimer’s disease and certain cancers.',
  },
  fibrinogen: {
    title: 'Fibrinogen Q',
    normal_range: [[3.0, 3.9]],
    abnormal_range: [
      [0.0, 2.0],
      [3.9, 99],
    ],
    optimal_range: [[2.0, 3.0]],
    unit: 'g/L',
    desc: "The Fibrinogen Quantitative test measures the amount of fibrinogen in the blood. Fibrinogen is a protein produced by the liver and is essential for blood clotting. When there is an injury, fibrinogen is converted into fibrin, which helps form a blood clot to stop bleeding. The quantitative measurement of fibrinogen is used to evaluate a person's ability to form blood clots and to diagnose or monitor conditions that affect clotting, such as bleeding disorders, liver disease, and conditions associated with abnormal clotting, like disseminated intravascular coagulation (DIC). Elevated or reduced levels of fibrinogen can indicate various health issues, including inflammation, cardiovascular diseases ( heart attack and stroke), and other underlying conditions such as cancer, especially colon cancer. Low fibrinogen levels may indicate liver disease or dysfunction, as the liver is responsible for producing fibrinogen. On the other hand, high fibrinogen levels (greater than 3.00 g/L) can be a marker for several serious health conditions. These include an increased risk of cardiovascular diseases, such as coronary artery disease, heart attacks, and strokes, as well as clot-related events like deep vein thrombosis (DVT) or pulmonary embolism. Elevated fibrinogen levels are also associated with metabolic syndrome, including type 2 diabetes, certain cancers, and pregnancy complications such as preeclampsia or placental abruption.",
  },
  creatineKinase: {
    title: 'Creatine Kinase',
    normal_range: [[33.0, 65.0]],
    abnormal_range: [
      [0.0, 33.0],
      [65.0, 999],
    ],
    optimal_range: [[0.0, 33.0]],
    unit: 'U/L',
    desc: 'Creatine Kinase (CK) is an enzyme that plays a vital role in energy metabolism within cells, particularly in tissues that require a lot of energy, such as muscles, the heart, and the brain. CK catalyzes the conversion of creatine and uses ATP (adenosine triphosphate) to create phosphocreatine and ADP (adenosine diphosphate). This reaction is crucial for maintaining a readily available supply of energy in cells, especially during intense physical activity. Elevated CK levels are most commonly associated with muscle damage. This can result from physical injuries, intense exercise, muscle diseases like rhabdomyolysis, or conditions like muscular dystrophy. CK-MB levels are used as a marker for heart attacks. Although more specific markers like troponin are now preferred, CK-MB is still valuable in certain clinical settings. Individuals with greater muscle mass naturally have higher CK levels.',
  },
  apoB: {
    title: 'Apolipoprotein B',
    normal_range: [[0.8, 1.0]],
    abnormal_range: [[1.0, 99]],
    optimal_range: [[0.0, 0.8]],
    unit: 'g/L',
    desc: '',
  },
  lpA: {
    title: 'Lp(a)',
    normal_range: [[0.0, 75.0]],
    abnormal_range: [[75.0, 999]],
    optimal_range: [[0.0, 30.0]],
    unit: 'nmol/L',
    desc: '',
  },
  homocysteine: {
    title: 'Homocysteine',
    normal_range: [[0.0, 15.0]],
    abnormal_range: [[15.0, 99]],
    optimal_range: [[0.0, 10.0]],
    unit: 'μmol/L',
    desc: '',
  },
  uricAcid: {
    title: 'Uric Acid',
    normal_range: [[210.0, 420.0]],
    abnormal_range: [
      [0.0, 210.0],
      [420.0, 999],
    ],
    optimal_range: [[250.0, 350.0]],
    unit: 'μmol/L',
    desc: 'Uric acid is a chemical compound that is a byproduct of the breakdown of purines, which are substances found in certain foods and are also naturally occurring in the body. Uric acid is normally dissolved in the blood and excreted from the body through the kidneys into the urine. Uric acid is an important indicator used in medical diagnostics to assess and monitor various health conditions, particularly those related to metabolic processes, kidney function, and cardiovascular health.',
  },
  follitropin: {
    title: 'FSH',
    normal_range: [[1.0, 15.0]],
    abnormal_range: [
      [0.0, 1.0],
      [15.0, 999],
    ],
    optimal_range: [[3.0, 15.0]],
    unit: 'IU/L',
    desc: 'Follicle-Stimulating Hormone (FSH), produced by the anterior pituitary gland, is essential for female reproductive health. It stimulates the growth of ovarian follicles, necessary for ovulation and estradiol production, which prepares the endometrium for pregnancy. FSH levels help assess ovarian reserve and diagnose conditions like infertility, PCOS, and primary ovarian insufficiency (POI). High FSH may indicate reduced ovarian reserve or menopause, while low FSH could suggest PCOS, hypothalamic amenorrhea, or pituitary dysfunction.\nLow FSH Implications:\n• Pituitary Hypofunction: Low FSH may indicate an underactive pituitary gland, affecting other hormones and overall hormonal balance.\n• Polycystic Ovary Syndrome (PCOS): Characterized by low FSH and high LH levels, disrupting follicular development and causing symptoms like irregular periods, infertility, and elevated androgens.\nHigh FSH Implications:\n• Menopause: Elevated FSH levels, especially above 50 IU/L with a year of missed periods, signal menopause.\n• Ovarian Hypofunction: High FSH can also suggest ovarian failure, where insufficient estradiol impacts ovarian function and reproductive health.',
  },
  lutropin: {
    title: 'LH',
    normal_range: [[1.0, 12.0]],
    abnormal_range: [
      [0.0, 1.0],
      [12.0, 30.0],
    ],
    optimal_range: [[2.0, 12.0]],
    unit: 'IU/L',
    desc: 'Luteinizing Hormone (LH), produced by the anterior pituitary gland, is essential for reproductive health. It triggers ovulation, releasing a mature egg from the ovary, and supports the formation of the corpus luteum, which produces progesterone to maintain the uterine lining for potential pregnancy. Low LH levels may signal reproductive issues like anovulation or hypothalamic amenorrhea. In postmenopausal women, elevated LH is normal, but persistently low levels may indicate pituitary dysfunction.\nLow LH Implications:\n• Pituitary Hypofunction: Low LH can suggest an underactive pituitary gland, affecting other hormones and overall endocrine balance.\nHigh LH Implications:\n• Ovarian Hypofunction or Failure: High LH levels may indicate the ovaries are not producing enough progesterone, impairing reproductive health.\n• Polycystic Ovary Syndrome (PCOS): Characterized by high LH and low FSH levels, leading to an elevated LH-to-FSH ratio. This imbalance disrupts follicular development and ovulation, contributing to symptoms like irregular periods, infertility, and elevated androgens.\n• Menopause: Elevated LH levels, particularly above normal, signal the transition into menopause and the decline of ovarian function.',
  },
  estradiol: {
    title: 'Estradiol',
    normal_range: [[77.0, 921.0]],
    abnormal_range: [
      [0.0, 77.0],
      [921.0, 9999],
    ],
    optimal_range: [[77.0, 921.0]],
    unit: 'pmol/mL',
    desc: 'Estradiol (E2) is the most potent estrogen and is primarily produced by the ovaries. It plays a key role in regulating the reproductive system, including the development of secondary sexual characteristics, and is essential for maintaining bone health, cardiovascular function, and cognitive balance. Estradiol levels vary throughout the menstrual cycle, typically peaking just before ovulation and falling if pregnancy does not occur.\nLow Estradiol Implications:\n• Menopause: Low levels of estradiol are characteristic of menopause, indicating a natural decline in ovarian function.\n• Osteoporosis: Insufficient estradiol contributes to decreased bone density, increasing the risk of osteoporosis and fractures.\nHigh Estradiol Implications:\n• Cancer Risk: Elevated estradiol levels are associated with an increased risk of developing breast or endometrial cancer, highlighting the need for careful monitoring in affected individuals.',
  },
  progesterone: {
    title: 'Progesterone',
    normal_range: [[0.0, 1.7]],
    abnormal_range: [[1.7, 99]],
    optimal_range: [[0.0, 1.7]],
    unit: 'nmol/L',
    desc: 'Progesterone (P4) is essential for regulating the menstrual cycle and supporting pregnancy. Produced by the corpus luteum after ovulation, it prepares the uterine lining for implantation and maintains it during early pregnancy. If pregnancy doesn’t occur, progesterone levels drop, leading to menstruation.\nLow Progesterone Implications:\n• Menopause: Common in postmenopausal women due to reduced ovarian function.\n• Polycystic Ovary Syndrome (PCOS): Low levels result from anovulation, causing irregular periods.\n• Cancer Risk: Insufficient progesterone can increase breast and endometrial cancer risk by allowing unopposed estradiol effects.\nHigh Progesterone Implications:\n• Pregnancy: Elevated levels are crucial for maintaining the uterine environment.\n• Health Benefits: Helps manage symptoms like bloating and migraines, reduces fibroid size, and lowers risks of osteoporosis, fibrocystic breast disease, and ovarian cancer.',
  },
  testosterone: {
    title: 'Total Testosterone',
    normal_range: [[2.0, 28.0]],
    abnormal_range: [
      [0.0, 2.0],
      [38.0, 999],
    ],
    optimal_range: [[3.0, 38.0]],
    unit: 'nmol/L',
    desc: 'Testosterone in women, produced mainly by the ovaries and adrenal glands, is crucial for muscle mass, bone density, and overall energy. It regulates libido, mood, and cognitive function. Despite being more associated with men, testosterone in women impacts sexual function, mood, energy, and skin health. Total Testosterone: This measures the overall amount of testosterone in the blood, including both bound and free forms. It helps diagnose conditions like polycystic ovary syndrome (PCOS), adrenal disorders, and other hormonal imbalances. Testosterone levels naturally fluctuate during the menstrual cycle and decline with age, particularly after menopause. Imbalances can lead to various health issues, including reduced energy, bone strength, and libido, as well as skin changes.',
  },
  testosteroneFree: {
    title: 'Free Testosterone',
    normal_range: [[0.0, 636.0]],
    abnormal_range: [[636.0, 9999]],
    optimal_range: [[26.0, 700.0]],
    unit: 'pmol/L',
    desc: 'Free testosterone refers to the small fraction of total testosterone that is not bound to any proteins in the blood, making it bioavailable and capable of exerting its effects on the body. Although it constitutes only a small percentage of total testosterone, free testosterone is considered the active form of the hormone, directly influencing various physiological processes such as libido, muscle mass, bone density, and mood.',
  },
  dhea: {
    title: 'DHEA',
    normal_range: [[0.0, 10.0]],
    abnormal_range: [[10.0, 20.0]],
    optimal_range: [[5.0, 20.0]],
    unit: 'umol/L',
    desc: 'Dehydroepiandrosterone (DHEA) is a steroid hormone produced mainly by the adrenal glands and, in smaller amounts, by the ovaries. It serves as a precursor to crucial hormones like androgens, progesterone, and estradiol. DHEA plays a key role in hormone synthesis, sexual function, energy levels, immune response, and mood regulation.\nDHEA levels peak in early adulthood and decline with age, which can lead to various age-related conditions, including metabolic syndrome, cardiovascular disease, osteoporosis, mood disorders, and sexual dysfunction. Maintaining youthful DHEA levels is beneficial for long-term health and well-being.\nClinical Implications of Low DHEA Levels:\n• Adrenal Insufficiency: Low levels may indicate inadequate hormone production by the adrenal glands.\n• Hyperinsulinemia: Reduced DHEA is linked to high insulin levels, often related to insulin resistance.\n• Immune Insufficiency: Low DHEA can weaken immune function.\n• Age-Related Conditions: Low levels are associated with conditions like metabolic syndrome, coronary artery disease, osteoporosis, mood disorders, and sexual dysfunction.\nClinical Implications of Elevated DHEA Levels:\n• Adrenal Hyperplasia: High levels may suggest a condition where the adrenal glands are unable to produce glucocorticoids effectively.',
  },
  prolactin: {
    title: 'Prolactin',
    normal_range: [[4.0, 27.0]],
    abnormal_range: [
      [0.0, 4.0],
      [27.0, 999],
    ],
    optimal_range: [[5.0, 27.0]],
    unit: 'ug/L',
    desc: 'Prolactin, a peptide hormone from the anterior pituitary gland, is key for milk production and reproductive health. It prepares breasts for breastfeeding during pregnancy and maintains milk supply after childbirth. Prolactin also supports breast tissue development and progesterone production. Regulated by the hypothalamus with input from thyrotropin-releasing hormone (TRH) and dopamine, prolactin levels peak at night. High prolactin levels, or hyperprolactinemia, can disrupt menstrual cycles and ovulation, potentially leading to infertility. Causes of elevated prolactin include stress, medications, and conditions like prolactinoma or hypothyroidism. Testing prolactin levels helps diagnose issues such as unexpected milk production and menstrual irregularities.',
  },
  sexHormoneBindGlobulin: {
    title: 'Sex Hormone (SHBG)',
    normal_range: [[20.0, 80.0]],
    abnormal_range: [
      [0.0, 20.0],
      [180.0, 9999],
    ],
    optimal_range: [[80.0, 180.0]],
    unit: 'nmol/L',
    desc: 'Sex Hormone-Binding Globulin (SHBG) is a glycoprotein produced mainly by the liver, with smaller amounts from the uterus, brain, and placenta. It regulates sex hormones like testosterone and estrogen by binding to them, which reduces their activity in the bloodstream. This regulation helps maintain hormonal balance and affects reproductive health, mood, and metabolism.\nSHBG levels are influenced by age, hormone levels, insulin resistance, obesity, and medications. Higher SHBG levels are linked to better metabolic outcomes, including improved insulin sensitivity, lower risk of type 2 diabetes, and reduced cardiovascular disease risk. Maintaining high SHBG levels supports overall health and longevity by enhancing glucose regulation and reducing metabolic disorders.',
  },
  cortisolAm: {
    title: 'AM Cortisol',
    normal_range: [
      [130.0, 250.0],
      [350.0, 540.0],
    ],
    abnormal_range: [
      [0.0, 130.0],
      [540.0, 9999],
    ],
    optimal_range: [[250.0, 350.0]],
    unit: 'nmol/L',
    desc: "Cortisol is a steroid hormone produced by the adrenal glands, essential for regulating stress, metabolism, immune function, and blood sugar levels. It follows a daily rhythm, peaking in the morning and declining by evening. Measuring morning cortisol helps diagnose adrenal conditions like Cushing's syndrome (excess cortisol) and Addison's disease (insufficient cortisol).\nLow Cortisol Levels:\n• Adrenal Insufficiency (Addison's Disease): Causes fatigue, muscle weakness, and low blood pressure.\n• Hypoglycemia: Impairs blood sugar regulation, leading to dizziness and confusion.\n• Fatigue and Weakness: Results in chronic tiredness and muscle weakness.\n• Hypotension: Leads to low blood pressure, causing dizziness and fainting.\n• Electrolyte Imbalance: Disrupts sodium and potassium balance, causing dehydration and confusion.\n• Reduced Immune Function: Weakens immune responses.\n• Mental Health Issues: Linked to depression, anxiety, and cognitive problems.\n• Adrenal Crisis: Severe deficiency requires urgent treatment.\nHigh Cortisol Levels:\n• Cushing's Syndrome: Causes weight gain, thinning skin, and high blood pressure.\n• Hypertension: Increases blood pressure and fluid retention.\n• Hyperglycemia and Insulin Resistance: Leads to high blood sugar and risk of type 2 diabetes.\n• Osteoporosis: Reduces bone density and increases fracture risk.\n• Immune Suppression: Impairs immune function.\n• Weight Gain and Obesity: Promotes fat accumulation, especially around the abdomen.\n• Mood Disorders: Contributes to depression, anxiety, and cognitive issues.\n• Gastrointestinal Issues: Causes acid reflux and ulcers.\n• Sleep Disturbances: Disrupts sleep patterns and quality.\n• Menstrual Irregularities and Infertility: Affects menstrual cycles and fertility in women.",
  },
  totalPsa: {
    title: 'Total PSA',
    normal_range: [[0.0, 2.5]],
    abnormal_range: [[2.5, 9999.0]],
    optimal_range: [[0.0, 1.0]],
    unit: 'ug/L',
    desc: 'Prostate-Specific Antigen (PSA) is a protein produced primarily by cells in the prostate gland, and it is used as a biomarker for prostate health in males. PSA testing typically involves measuring the total PSA, free PSA, and calculating the free-to-total PSA ratio. Each of these measures provides valuable information for assessing prostate conditions, including benign prostatic hyperplasia (BPH) and prostate cancer risk.',
  },
  hemoglobin: {
    title: 'Hemoglobin',
    normal_range: [[120.0, 175.0]],
    abnormal_range: [
      [0.0, 120.0],
      [175.0, 9999],
    ],
    optimal_range: [[130.0, 155.0]],
    unit: 'g/L',
    desc: "Hemoglobin is a protein in red blood cells that carries oxygen from the lungs to the body's tissues and returns carbon dioxide back to the lungs. Adequate hemoglobin levels are essential for maintaining energy, brain function, and tissue health. Low hemoglobin may indicate anemia, while elevated levels may reflect dehydration, lung disease, or other medical conditions.",
  },
  hematocrit: {
    title: 'Hematocrit (HCT)',
    normal_range: [[0.35, 0.5]],
    abnormal_range: [
      [0.0, 0.35],
      [0.5, 99],
    ],
    optimal_range: [[0.37, 0.44]],
    unit: 'L/L',
    desc: 'Hematocrit measures the proportion of blood volume occupied by red blood cells. It provides insight into oxygen-carrying capacity and hydration status. Low hematocrit may signal anemia or blood loss, while high levels can suggest dehydration or polycythemia.',
  },
  wbc: {
    title: 'WBC',
    normal_range: [[3.2, 11.0]],
    abnormal_range: [
      [0.0, 3.2],
      [11.0, 999],
    ],
    optimal_range: [[4.0, 10.0]],
    unit: 'xE9/L',
    desc: 'White Blood Cell (WBC) count reflects the body’s immune activity. Elevated levels may indicate infection, inflammation, or immune disorders, while low levels can suggest bone marrow suppression, viral infection, or immune deficiency.',
  },
  neutrophils: {
    title: 'Neutrophils',
    normal_range: [[1.4, 7.5]],
    abnormal_range: [
      [0.0, 1.4],
      [7.5, 99],
    ],
    optimal_range: [[2.0, 7.5]],
    unit: 'xE9/L',
    desc: 'Neutrophils are the most abundant type of white blood cells and the first responders to infections. Elevated neutrophils often indicate bacterial infections or inflammation; low levels may suggest bone marrow disorders or certain viral infections.',
  },
  lymphocytes: {
    title: 'Lymphocytes',
    normal_range: [[1.0, 3.5]],
    abnormal_range: [
      [0.0, 1.0],
      [3.5, 99],
    ],
    optimal_range: [[1.0, 3.5]],
    unit: 'xE9/L',
    desc: 'Lymphocytes are white blood cells involved in adaptive immune responses. High lymphocyte counts may indicate viral infections or certain blood cancers, while low levels can occur in immune suppression or chronic illness.',
  },
  monocytes: {
    title: 'Monocytes',
    normal_range: [[0.2, 1.0]],
    abnormal_range: [
      [0.0, 0.2],
      [1.0, 99],
    ],
    optimal_range: [[0.2, 1.0]],
    unit: 'xE9/L',
    desc: 'Monocytes are immune cells that help remove pathogens and dead cells. Elevated monocyte levels may indicate chronic infections, inflammation, or autoimmune conditions, while low levels are typically less concerning.',
  },
  eosinophils: {
    title: 'Eosinophils',
    normal_range: [[0.0, 0.5]],
    abnormal_range: [[0.5, 99]],
    optimal_range: [[0.0, 0.5]],
    unit: 'xE9/L',
    desc: 'Eosinophils are white blood cells involved in allergic reactions and parasitic infections. Elevated eosinophil levels can signal allergies, asthma, or parasitic disease, while low levels are generally not clinically significant.',
  },
  rbc: {
    title: 'RBC',
    normal_range: [[4.0, 6.0]],
    abnormal_range: [
      [0.0, 4.0],
      [6.0, 99],
    ],
    optimal_range: [[4.3, 4.8]],
    unit: 'xE12/L',
    desc: 'Red Blood Cells (RBCs) transport oxygen to tissues. Low RBC counts may suggest anemia or bleeding, while high levels may be due to dehydration, lung disease, or polycythemia vera. Balanced RBC levels are critical for energy and cellular function.',
  },
  mcv: {
    title: 'MCV',
    normal_range: [
      [80.0, 82.0],
      [90.0, 100.0],
    ],
    abnormal_range: [
      [0.0, 80.0],
      [100.0, 999],
    ],
    optimal_range: [[82.0, 90.0]],
    unit: 'fL',
    desc: 'Mean Corpuscular Volume (MCV) reflects the average size of red blood cells. Low MCV suggests microcytic anemia (often due to iron deficiency), while high MCV points to macrocytic anemia, commonly caused by vitamin B12 or folate deficiency.',
  },
  mch: {
    title: 'MCH',
    normal_range: [[27.5, 33.0]],
    abnormal_range: [
      [0.0, 27.5],
      [33.0, 999],
    ],
    optimal_range: [[27.5, 33.0]],
    unit: 'pg',
    desc: 'Mean Corpuscular Hemoglobin (MCH) indicates the average amount of hemoglobin per red blood cell. Low MCH can indicate iron-deficiency anemia, while high MCH may occur in macrocytic anemias.',
  },
  mchc: {
    title: 'MCHC',
    normal_range: [[305.0, 360.0]],
    abnormal_range: [
      [0.0, 305.0],
      [360.0, 9999],
    ],
    optimal_range: [[305.0, 360.0]],
    unit: 'g/L',
    desc: 'Mean Corpuscular Hemoglobin Concentration (MCHC) measures the concentration of hemoglobin in red blood cells. Low MCHC often indicates hypochromic anemia, while elevated MCHC can be associated with hereditary spherocytosis or other disorders.',
  },
  rdw: {
    title: 'RDW',
    normal_range: [[11.5, 17.3]],
    abnormal_range: [
      [0.0, 11.5],
      [17.3, 999],
    ],
    optimal_range: [[11.5, 14.5]],
    unit: '%',
    desc: 'Red Cell Distribution Width (RDW) assesses the variation in red blood cell size. High RDW suggests mixed anemia types (e.g., iron and B12 deficiency), while normal RDW with anemia may indicate a single cause.',
  },
  plateletCount: {
    title: 'Platelet Count',
    normal_range: [[150.0, 400.0]],
    abnormal_range: [
      [0.0, 150.0],
      [400.0, 9999],
    ],
    optimal_range: [[190.0, 350.0]],
    unit: 'xE9/L',
    desc: 'Platelets are small cell fragments involved in blood clotting. Low platelet counts (thrombocytopenia) increase bleeding risk, while high counts (thrombocytosis) may reflect inflammation, infection, or bone marrow disorders.',
  },
  vitaminB12: {
    title: 'Vitamin B12',
    normal_range: [[220.0, 652.0]],
    abnormal_range: [
      [0.0, 220.0],
      [652.0, 800.0],
    ],
    optimal_range: [[800.0, 9999]],
    unit: 'pmol/L',
    desc: 'Vitamin B12, also known as cobalamin, is a crucial water-soluble vitamin with key roles in red blood cell production, nervous system maintenance, and DNA synthesis. It is indispensable for neurological function and cellular metabolism, particularly influencing DNA synthesis and regulation, fatty acid metabolism, and energy production. Naturally present in animal products such as meat, fish, eggs, and dairy, Vitamin B12 can also be supplemented. Its absorption is a complex process requiring intrinsic factor, a stomach-produced protein. Without intrinsic factor, effective absorption of Vitamin B12 in the small intestine is impaired, potentially leading to deficiency. The majority of Vitamin B12 is stored in the liver, with additional reserves in the bone marrow and other tissues. A deficiency can result in significant health issues, including pernicious anemia, neuropathy, and cognitive impairments like memory loss or confusion. Common symptoms of deficiency include fatigue, weakness, constipation, loss of appetite, and numbness or tingling in the extremities.',
  },
  vitaminD: {
    title: 'Vitamin D (25-hydroxy)',
    normal_range: [[76.0, 200.0]],
    abnormal_range: [
      [0.0, 76.0],
      [250.0, 999],
    ],
    optimal_range: [[200.0, 250.0]],
    unit: 'nmol/L',
    desc: 'Vitamin D 25(OH), or 25-hydroxyvitamin D, is the main form of vitamin D in the blood and the best indicator of vitamin D levels. Produced in the liver from vitamin D3 or D2, it is measured to detect deficiencies or excesses, which can lead to rickets, osteomalacia, osteoporosis, or hypercalcemia. Vitamin D acts as a hormone: UVB rays convert skin cholesterol to vitamin D3, which the liver then turns into 25(OH)D. This metabolite is further converted in the kidneys to calcitriol (1,25-dihydroxyvitamin D), the active form that regulates calcium and phosphate levels and supports bone health. Calcitriol, made from 25(OH)D in the liver and kidneys, can also be produced by other tissues. It influences the immune system and is regulated by parathyroid hormone, calcium, and phosphate. While not a primary marker of vitamin D status, calcitriol measurement can help in specific conditions like vitamin D metabolism disorders and certain diseases.',
  },
  vitaminA: {
    title: 'Vitamin A',
    normal_range: [
      [1.2, 1.99],
      [3.0, 3.5],
    ],
    abnormal_range: [
      [0.0, 1.2],
      [3.5, 99],
    ],
    optimal_range: [[1.99, 3.0]],
    unit: 'umol/L',
    desc: 'Vitamin A is a fat-soluble vitamin essential for numerous physiological functions in the body. It exists in two primary forms: preformed Vitamin A (retinoids), found in animal products such as liver, fish, and dairy, and provitamin A (carotenoids), found in plant-based foods like carrots, sweet potatoes, and leafy greens. The most common carotenoid, beta-carotene, is converted by the body into active Vitamin A as needed. Vitamin A is crucial for maintaining normal vision, particularly in low-light conditions, as it is a key component of rhodopsin, a protein in the retina that absorbs light. It also supports the immune system by preserving the integrity and function of skin and mucosal cells, which act as barriers against infections, and by enhancing the production and activity of white blood cells. Additionally, Vitamin A is essential for cellular growth and differentiation, particularly in the development and maintenance of epithelial tissues, including the skin and the linings of the respiratory, urinary, and digestive tracts. It also plays a significant role in reproductive health and embryonic development. A deficiency in Vitamin A can lead to several health issues, including night blindness, an increased susceptibility to infections, and xerophthalmia. Severe deficiency may also cause skin disorders and compromised immune function. Given that Vitamin A is fat-soluble, excessive intake, particularly of preformed Vitamin A, can lead to toxicity, known as hypervitaminosis A. This condition can result in symptoms such as nausea, headache, dizziness, and, in severe cases, liver damage, bone loss, and central nervous system disorders.',
  },
  sodium: {
    title: 'Sodium',
    normal_range: [
      [135.0, 137.0],
      [142.0, 146.0],
    ],
    abnormal_range: [
      [0.0, 135.0],
      [146.0, 999],
    ],
    optimal_range: [[137.0, 142.0]],
    unit: 'mmol/L',
    desc: 'Sodium is a crucial electrolyte that maintains fluid balance, nerve function, and muscle contraction. Found mainly in extracellular fluid, it helps regulate water balance and blood pressure and works with potassium and chloride to manage cellular water distribution. Sodium is essential for nerve signal transmission and muscle contraction, as it generates the electrical impulses needed for these processes. The kidneys regulate sodium levels by excreting excess sodium or retaining it as needed, with aldosterone playing a key role in this regulation. Abnormal sodium levels can cause hyponatremia (low sodium) or hypernatremia (high sodium), linked to conditions like dehydration, kidney disease, heart failure, and adrenal disorders. Proper sodium balance is crucial for overall health, especially for those with electrolyte imbalances.',
  },
  potassium: {
    title: 'Potassium',
    normal_range: [
      [3.5, 4.0],
      [5.0, 5.4],
    ],
    abnormal_range: [
      [0.0, 3.5],
      [5.4, 99],
    ],
    optimal_range: [[4.0, 5.0]],
    unit: 'mmol/L',
    desc: 'Potassium is a crucial mineral found mainly inside cells, essential for cellular functions like fluid balance, nerve signal transmission, and muscle contractions. It supports nerve and muscle function, including heart muscles, and helps regulate blood pressure and hydration. Potassium is present in fruits (bananas, oranges), vegetables (spinach, potatoes), legumes, nuts, and dairy. The kidneys control potassium levels, influenced by hormones like aldosterone. Imbalances can cause health issues: low potassium (hypokalemia) may lead to muscle weakness and arrhythmias, while high potassium (hyperkalemia) can result in serious heart problems. Monitoring potassium is especially important for those with kidney disease, heart failure, or on certain medications, as maintaining optimal levels is key for cardiovascular and muscular health.',
  },
  phosphorus: {
    title: 'Phosphorus',
    normal_range: [
      [0.8, 0.84],
      [1.2, 1.5],
    ],
    abnormal_range: [
      [0.0, 0.8],
      [1.5, 99],
    ],
    optimal_range: [[0.84, 1.2]],
    unit: 'mmol/L',
    desc: '',
  },
  alkalinePhosphate: {
    title: 'ALP',
    normal_range: [
      [40.0, 45.0],
      [100.0, 129.0],
    ],
    abnormal_range: [
      [0.0, 35.0],
      [129.0, 999],
    ],
    optimal_range: [[45.0, 100.0]],
    unit: 'U/L',
    desc: "Alkaline Phosphatase (ALP) is an enzyme mainly found in the liver, bones, kidneys, and biliary tract, with smaller amounts in the intestines and placenta. It removes phosphate groups from molecules in an alkaline environment and is a key marker of bone activity, particularly osteoblastic activity. Low ALP levels can indicate zinc deficiency or hypophosphatasia, a rare bone disorder. High ALP levels may signal conditions such as Paget's disease, bone metastases, healing fractures, or liver and biliary tract issues like cholestasis, hepatitis, and bile duct obstruction. Elevated ALP not related to the liver can also occur during normal bone growth in children or fracture healing. ALP levels are often measured in liver function tests to evaluate hepatobiliary health and bone diseases, including those with increased osteoblastic activity and metastatic bone cancer.",
  },
  alanineTransaminase: {
    title: 'ALT',
    normal_range: [[0.0, 50.0]],
    abnormal_range: [[50.0, 999]],
    optimal_range: [[0.0, 50.0]],
    unit: 'U/L',
    desc: 'Alanine Aminotransferase (ALT), also known as serum glutamate-pyruvate transaminase (SGPT), is an enzyme primarily found in the liver and to a lesser extent in the kidneys, heart, and muscles. ALT is essential for amino acid metabolism, converting alanine and α-ketoglutarate into pyruvate and glutamate. It is released into the blood when liver cells are damaged, making it a key marker for liver health. Elevated ALT levels can indicate liver damage from conditions like fatty liver, hepatitis, cirrhosis, and liver ischemia. Low levels may result from vitamin B6 deficiency or early-stage fatty liver disease. ALT is often measured with aspartate aminotransferase (AST) to assess liver-specific damage and differentiate between alcoholic and non-alcoholic liver diseases. ALT results should be interpreted with other tests, such as bilirubin and alkaline phosphatase, for a full evaluation of liver function and overall health.',
  },
  aspartateTransaminase: {
    title: 'AST',
    normal_range: [
      [0.0, 10.0],
      [30.0, 35.0],
    ],
    abnormal_range: [[35.0, 999]],
    optimal_range: [[10.0, 30.0]],
    unit: 'U/L',
    desc: 'Aspartate Aminotransferase (AST), or serum glutamate-oxaloacetate transaminase (SGOT), is an enzyme present in the liver, heart, muscles, kidneys, brain, and red blood cells. It is involved in amino acid metabolism by converting aspartate and α-ketoglutarate into oxaloacetate and glutamate. AST levels are used to evaluate liver function and detect damage. High levels can indicate liver conditions like hepatitis or cirrhosis, as well as heart or muscle damage. Low levels may be due to vitamin B6 deficiency. AST is often measured with alanine aminotransferase (ALT) to differentiate liver-related issues from other causes. The AST/ALT ratio helps identify alcoholic liver disease, with a ratio greater than 1 suggesting severe liver damage, while a ratio less than 1 typically indicates less severe liver disease.',
  },
  gammaGlutamylTransferase: {
    title: 'GGT',
    normal_range: [[50.0, 62.0]],
    abnormal_range: [
      [0.0, 10.0],
      [62.0, 999],
    ],
    optimal_range: [[10.0, 50.0]],
    unit: 'U/L',
    desc: 'Gamma-Glutamyl Transferase (GGT) is an enzyme primarily in the liver, with lesser amounts in the kidneys, pancreas, and bile ducts. It aids in amino acid transfer and glutathione metabolism. Elevated GGT levels indicate liver or bile duct issues, such as cholestasis, hepatitis, cirrhosis, and liver tumors. It is also a marker for chronic alcohol abuse, often remaining high in heavy drinkers. GGT can help distinguish between liver and bone diseases when measured with alkaline phosphatase (ALP), with a high GGT/ALP ratio suggesting liver or bile duct disease. Low GGT levels may be linked to vitamin B6 and magnesium deficiencies. GGT monitoring is useful for assessing liver function, antioxidant status, and susceptibility to oxidative stress. Men may have higher normal GGT levels due to its presence in the prostate.',
  },
  totalBilirubin: {
    title: 'Total Bilirubin',
    normal_range: [
      [0.0, 5.0],
      [15.0, 20.0],
    ],
    abnormal_range: [[20.0, 999]],
    optimal_range: [[5.0, 15.0]],
    unit: 'umol/L',
    desc: 'Bilirubin is a yellow pigment from the breakdown of hemoglobin in red blood cells. The liver processes it into a water-soluble form for excretion in bile. Bilirubin exists in two forms: • Unconjugated (Indirect): Produced from hemoglobin breakdown, not water-soluble, and transported to the liver bound to albumin. • Conjugated (Direct): Processed in the liver, water-soluble, and excreted in bile. Measuring bilirubin levels helps assess liver function, diagnose jaundice, and identify bile duct issues. Elevated levels can indicate excessive red blood cell breakdown, liver dysfunction, or bile duct obstruction, causing conditions like jaundice, hepatitis, cirrhosis, or gallstones. Low levels may suggest oxidative stress. High total bilirubin levels require assessing both direct and indirect forms to determine the cause, whether prehepatic (e.g., hemolysis) or posthepatic (e.g., obstruction). Subtracting one bilirubin value from the total helps clarify the diagnosis.',
  },
  albumin: {
    title: 'Albumin',
    normal_range: [[35.0, 45.0]],
    abnormal_range: [
      [0.0, 35.0],
      [52.0, 999],
    ],
    optimal_range: [[45.0, 52.0]],
    unit: 'g/L',
    desc: "Albumin is a type of protein found in the blood, produced by the liver, and it performs several crucial functions. Firstly, it helps maintain blood volume and pressure by preventing fluid from leaking out of blood vessels and into tissues. Secondly, albumin binds to various substances, such as hormones, vitamins, and drugs, and transports them throughout the bloodstream. Additionally, it acts as a buffer to help regulate the blood's pH levels. Low levels of albumin in the blood can indicate issues such as liver disease, kidney disease, or other medical conditions.",
  },
  thyroidStimulatingHormone: {
    title: 'TSH',
    normal_range: [[1.0, 4.0]],
    abnormal_range: [
      [0.0, 0.32],
      [4.0, 99],
    ],
    optimal_range: [[0.32, 1.0]],
    unit: 'mIU/L',
    desc: "TSH, produced by the pituitary gland, regulates thyroid hormone production (T4 and T3). Its levels reflect thyroid function: high TSH signals low thyroid hormones, while low TSH suggests high thyroid hormones or possible pituitary or hypothalamic issues. Low TSH: • Hyperthyroidism: Check for conditions like Hashimoto's or Graves' disease or contributing factors. • Secondary Hypothyroidism: Indicates pituitary dysfunction if TSH is low but T3 and T4 are normal. • Tertiary Hypothyroidism: Results from hypothalamic issues, often linked to chronic fatigue syndrome. • Heavy Metal Toxicity: Consider if thyroid issues persist despite treatment. High TSH: • Primary Hypothyroidism: Indicates the thyroid gland is underactive, often due to autoimmune disorders, and is associated with high cholesterol and triglycerides.",
  },
  freeT4: {
    title: 'Free T4',
    normal_range: [[9.0, 10.0]],
    abnormal_range: [
      [0.0, 9.0],
      [23.0, 999],
    ],
    optimal_range: [[10.0, 23.0]],
    unit: 'pmol/L',
    desc: 'Free T4 (free thyroxine) is the portion of the thyroid hormone T4 that is not bound to proteins, making it available to enter tissues and regulate metabolism, energy production, and metabolic rate. It is the active form of T4 and can be converted to the more potent T3 within cells. T4 production can be affected by nutrient levels such as zinc, copper, vitamin A, and B vitamins; deficiencies in these can lower T4 synthesis. High Free T4 levels typically indicate hyperthyroidism, while low levels are associated with hypothyroidism. T4 is converted to T3 or reverse T3 in peripheral tissues, a process dependent on nutrients like iodine, selenium, and tyrosine.',
  },
  freeT3: {
    title: 'Free T3',
    normal_range: [[2.6, 4.8]],
    abnormal_range: [
      [0.0, 2.6],
      [6.0, 99],
    ],
    optimal_range: [[4.8, 6.0]],
    unit: 'pmol/L',
    desc: 'Free T3 (free triiodothyronine) is the unbound, active form of the thyroid hormone T3, crucial for regulating metabolic processes, energy production, and growth. It affects metabolism at the cellular level, influences bone and muscle maintenance, and helps regulate body temperature. Most Free T3 is produced by converting T4 (thyroxine) in peripheral tissues like the liver and kidneys, with a smaller amount produced directly by the thyroid. About 8-10% of T3 in the blood is free and active, affecting mitochondrial function and cardiac health. Low Free T3: • Primary Hypothyroidism: An underactive thyroid gland leading to low Free T3. • Thyroid Conversion Syndrome: Normal thyroid function but impaired conversion of T4 to T3, often due to stress or malnutrition, showing normal TSH, low Free T3, and high reverse T3. • Secondary Hypothyroidism: Low Free T3 due to pituitary gland dysfunction. • Euthyroid Sick Syndrome: Low Free T3 with additional abnormalities like liver or renal dysfunction. • Selenium Deficiency: Reduced Free T3 despite normal TSH and T4, due to impaired conversion from T4. High Free T3: • Hyperthyroidism: Elevated Free T3 with low TSH levels. • Iodine Deficiency: Can cause high Free T3 with low T4 levels and normal or elevated TSH.',
  },
  reverseT3: {
    title: 'Reverse T3',
    normal_range: [
      [8.0, 10.0],
      [16.0, 25.0],
    ],
    abnormal_range: [
      [0.0, 8.0],
      [25.0, 999],
    ],
    optimal_range: [[10.0, 16.0]],
    unit: 'ng/dL',
    desc: "Reverse T3 (rT3) is an inactive form of T3 produced when thyroxine (T4) is converted into rT3 instead of active T3. Unlike T3, rT3 does not regulate metabolism. During stress or illness, rT3 levels rise to conserve energy and slow metabolism. High rT3 can cause symptoms similar to hypothyroidism, even if thyroid tests are normal. Elevated rT3 is associated with conditions like euthyroid sick syndrome, chronic stress, and nutritional deficiencies, acting as a 'metabolic brake' by blocking T3 from entering cells and reducing energy production.",
  },
  thyroidPeroxidaseAntibody: {
    title: 'anti-TPO',
    normal_range: [[0.0, 35.0]],
    abnormal_range: [[35.0, 999]],
    optimal_range: [[0.0, 35.0]],
    unit: 'kIU/mL',
    desc: "TPO Antibodies (anti-TPO, Thyroid Peroxidase Abs) Thyroid Peroxidase (TPO) antibodies are autoantibodies targeting the thyroid peroxidase enzyme, which is essential for the production of thyroid hormones. TPO facilitates the iodination of tyrosine residues on thyroglobulin, a critical step in synthesizing thyroxine (T4) and triiodothyronine (T3). The presence of TPO antibodies is strongly associated with autoimmune thyroid disorders, such as Hashimoto's thyroiditis and Graves' disease. In Hashimoto's thyroiditis, these antibodies contribute to the destruction of thyroid tissue, ultimately leading to hypothyroidism. In Graves' disease, TPO antibodies are often present, although they do not directly cause the condition; instead, they reflect an underlying autoimmune dysfunction. even when thyroid hormone levels remain within normal limits, making them a valuable marker for diagnosing and managing autoimmune thyroid diseases.",
  },
  thyroglobulinAntibodies: {
    title: 'anti-TG',
    normal_range: [[0.0, 41.0]],
    abnormal_range: [[41.0, 999]],
    optimal_range: [[0.0, 41.0]],
    unit: 'kIU/mL',
    desc: "Anti-Thyroglobulin (anti-TG) antibodies target thyroglobulin, a protein essential for thyroid hormone production. Their presence is linked to autoimmune thyroid disorders like Hashimoto's thyroiditis and Graves' disease, signaling an immune attack on the thyroid. Elevated anti-TG levels indicate ongoing autoimmune activity, even if other thyroid tests are normal. In thyroid cancer patients, monitoring these antibodies helps detect potential recurrence. However, anti-TG testing can yield false positives or negatives, as antibodies may appear in some individuals with normal thyroid function and fluctuate with immune system changes.",
  },
};
