name: Build

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Ensure you're using the version that matches your project

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run build step
      - name: Run React Build
        run: npm run build
